spring:
  profiles:
    active: local

---

spring:
  profiles: local

server:
  port: 8080

#logging:
#  level:
#    jdbc.sqlonly: info

spring.main.allow-bean-definition-overriding: true

---

spring:
  profiles: prod

server:
  port: 8081


spring.main.allow-bean-definition-overriding: true
#logging:
#  config: classpath:log4j2.properties
